---
# Copyright (c) 2025 Maxwell G <maxwell@gtmx.me>
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later
"on":
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

name: Test this action
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test ourselves
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      # Keep in sync with nox version in the README example
      - name: Install nox
        uses: wntrblm/nox@57f9e10c4eef84277dcd692d0056420c947674f9  # 2026.08.10

      - name: Test extra_args
        uses: $/
        with:
          sessions: extra_args
          working-directory: test
          extra-args: hello
